### ISSUE TITLE
Setup CI/CD Pipeline on IBM Cloud

### ISSUE THREAD

**Issue by RajathRD** [devops-recommendations/recommendations#109]
**As a** Developement Team
**We need** a CI/CD pipeline
**So that** we can push the latest changes to users fast and reliably.

**Assumptions**
We will use `behave` for integration tests and `nosetests` for Flask app tests.
We will use IBM Cloud to host our service.
We will have separate dev and prod instances setup.

**Acceptance Criteria**
When I commit a change to the master branch, the CI/CD pipeline must get triggered. 
The pipeline will have 4 stages 
- Build: this includes running unit tests
- Deploy to Dev: this involves deploying the code to the dev environment. 
- Integration test: this will run the behave tests against the dev instance
- Deploy to Prod: this involves deploying the changes to prod.

**Comment by amit4j** [comment]
Deployment pipeline - https://cloud.ibm.com/devops/pipelines/355f9d98-6bb4-4dbd-955b-3d47d29de2d0?env_id=ibm:yp:us-south
