### ISSUE TITLE
Deploy latest changes to cloud

### ISSUE THREAD

**Issue by RajathRD** [devops-recommendations/recommendations#112]
**As a** Developer
**I need** the ability to test the API on the cloud
**So that** I can refactor the service to integrate well with the CD pipeline.

**Assumptions**
We will use behave for integration tests

**Acceptance Criteria**
When I call GET <ibm-cloud-service-url>/recommendations I should see HTML results.

**Comment by amit4j** [comment]
Deployment done. Latest changes are live.
