### ISSUE TITLE
Improve test coverage and code format

### ISSUE THREAD

**Issue by RajathRD** [devops-recommendations/recommendations#28]
**As a** Development Team
**We need** to exhaustively test our service and follow the same code format
**So that ** our service is predictable, and our code is readable and standardized.

**Assumptions:**
We will be using Python, Flask and PyUnit.
We will be using pep8 standards and pylint.

**Acceptance Criteria:**

When I run `nosetests` 
I should see more than 95% overall test coverage.

Each file should get a pylint score of greater than 9.00 on 10.00

**Comment by xuanxuan12** [comment]
Current code coverage is 96%. @RajathRD could you please help check the pylint score.
