### ISSUE TITLE
Ability to test the recommendation service on a webpage

### ISSUE THREAD

**Issue by amit4j** [devops-recommendations/recommendations#3]
**As a** Tester
**I need** the ability to test API could see the worked page. 
**So that** check whether the API run successfully

**Assumptions**
A call to /recommendation/test should return a page saying "Welcome to the recommendations service"

**Acceptance Criteria**
When I call GET /recommendations I should see HTML results.

**Comment by amit4j** [comment]
@RajathRD The description of this story needs to be refined.

**Comment by RajathRD** [comment]
> @RajathRD The description of this story needs to be refined.

I agree. Will do it towards the end of the sprint.
