### ISSUE TITLE
Integrate Pull Requests with Slack channel

### ISSUE THREAD

**Issue by JennyHWAN** [devops-recommendations/recommendations#36]
**As a developer**
**I need** to be notified when someone makes a pull request.
**So that** I can approve it.

**Assumptions:**

I could be notified on Slack when someone makes pull request.

**Acceptance Criteria:**

- Any time someone makes a pull request, the channel is notified so someone can approve it.

**Comment by amit4j** [comment]
Enabled PRs for Pull requests.

**Comment by xuanxuan12** [comment]
Reviewed and will move it to Done.
