### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by JennyHWAN** [devops-recommendations/recommendations#39]
**As a** developer 
**I need** monitor GitHub repository for push and pull requests. 
**So that** ensure that the master branch is always deployable.

**Details & Assumptions:** 
* Use Travis CI to run your tests on every Pull Requests.

**Acceptance Criteria:**

* Set up Travis CI to monitor GitHub repository for push and pull requests.

**Comment by xuanxuan12** [comment]
Travis CI will not be used, and this issue is taken off from milestone and closed.
