### ISSUE TITLE
Add a Travis CI badge

### ISSUE THREAD

**Issue by JennyHWAN** [devops-recommendations/recommendations#40]
**As a** developer
**I need** a badge in `README.md` file
**So that** everyone will know if the build is broken.

**Details & Assumptions:** 

* The Pull Request will tell you if all of the tests have passed

**Acceptance Criteria:**

* Add a Travis CI badge to your `README.md` file so that everyone will know if the build is broken.

**Comment by xuanxuan12** [comment]
Travis CI will not be used, and this issue is taken off from milestone and closed.
