### ISSUE TITLE
Ability to query recommendations by recommendation type

### ISSUE THREAD

**Issue by xuanxuan12** [devops-recommendations/recommendations#42]
**As a** user  
**I need** to query the recommendations database  
**So that** I can search recommendations by recommendation type  

**Details & Assumptions:** 
* A call to GET /recommendations?type={type}&query_prod_id={id} should list the given type of recommendations related to product with given id in the database

**Acceptance Criteria:**

```gherkin
When I call GET /recommendations?type={type}&query_prod_id={id}
Then I should see the given type of recommendations related to product with given id
```

**Comment by amit4j** [comment]
The `prod_id` refers to the product for which we need the recommendation, right?

**Comment by xuanxuan12** [comment]
> The `prod_id` refers to the product for which we need the recommendation, right?

I believe prod_id here is query_prod_id, thank you for pointing out
