### ISSUE TITLE
Setup a CI pipeline

### ISSUE THREAD

**Issue by JennyHWAN** [devops-recommendations/recommendations#49]
**As a** developer
**I need** a CI pipeline
**So that** could monitor my GitHub repository for push and pull requests.

**Details & Assumptions:** 
* Should run on pull request
* Upload code coverage to codecov

**Acceptance Criteria:**

When a pull request is made
Then tests will run automatically and code coverage is uploaded to codecov

**Comment by amit4j** [comment]
@JennyHWAN I think we can merge this and the Integrate github actions story into one.

**Comment by amit4j** [comment]
@JennyHWAN We can close this issue.

**Comment by JennyHWAN** [comment]
Done in 'Integrate github actions'
